apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "nodejs_template"
  annotations:
    backstage.io/techdocs-ref: dir:./README.md
spec:
  type: service
  owner: user:guest
  lifecycle: experimental
